USE TMARKETUSED

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_TIPO_PAGO()
BEGIN
	SELECT *
    FROM TIPO_PAGO;
END$

call CONSULTA_GENERAL_TIPO_PAGO();

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_COMPRA()
BEGIN
	SELECT *
    FROM COMPRA;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_VENTA ()
BEGIN
	SELECT *
    FROM VENTA;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_ENVIO ()
BEGIN
	SELECT*
    FROM ENVIO;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_PEDIDO ()
BEGIN
	SELECT * 
    FROM PEDIDO ;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_CLIENTE ()
BEGIN
	SELECT *
    FROM CLIENTE;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_VENDEDOR()
BEGIN
	SELECT *
    FROM VENDEDOR;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_CARGO()
BEGIN
	SELECT *
    FROM CARGO;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_USUARIO ()
BEGIN
	SELECT *
    FROM USUARIO;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_SUBASTA ()
BEGIN
	SELECT *
	FROM SUBASTA;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_PUJA_SUBASTA ()
BEGIN
	SELECT *
    FROM PUJASUBASTA;
END$

DELIMITER $
CREATE PROCEDURE  CONSULTA_GENERAL_DESCRIPCION_PRODUCTO()
BEGIN
	SELECT *
	FROM DESCRIPCION_PRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_PRODUCTO()
BEGIN
	SELECT *
    FROM PRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_EXPERTO()
BEGIN
	SELECT *
    FROM EXPERTO;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_DETALLE_CLIENTE_PEDIDO ()
BEGIN
	SELECT *
    FROM DETALLE_CLIENTE_PEDIDO ;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_DETALLE_DESCRIPCION_PRODUCTO ()
BEGIN
	SELECT * 
    FROM DETALLE_DESCRIPCION_PRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE CONSULTA_GENERAL_DETALLE_PUJA_SUBASTA ()
BEGIN
	SELECT * 
    FROM DETALLE_PUJA_SUBASTA ;
END$