USE TMARKETUSED

DELIMITER $
CREATE PROCEDURE ELIMINAR_TIPO_PAGO(IN IDTIPOPAGO INT)
BEGIN
	DELETE FROM  TIPO_PAGO
	WHERE ID_TIPO_PAGO=IDTIPOPAGO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_COMPRA (IN IDCOMPRA INT)
BEGIN
	DELETE FROM COMPRA 
	WHERE ID_COMPRA=IDCOMPRA;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_VENTA (IN IDVENTA INT)
BEGIN
	DELETE FROM VENTA 
	WHERE ID_VENTA=IDVENTA;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_ENVIO (IN IDENVIO INT)
BEGIN
	DELETE FROM ENVIO 
	WHERE ID_ENVIO=IDENVIO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_PEDIDO (IN IDPEDIDO INT)
BEGIN
	DELETE FROM PEDIDO 
	WHERE ID_PEDIDO=IDPEDIDO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_CLIENTE (IN IDCLIENTE INT)
BEGIN
	DELETE FROM CLIENTE 
	WHERE ID_CLIENTE=IDCLIENTE;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_VENDEDOR (IN IDVENDEDOR INT)
BEGIN
	DELETE FROM VENDEDOR 
	WHERE ID_VENDEDOR=IDVENDEDOR;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_CARGO
(IN IDCARGO INT, IN NOMBRECARGO VARCHAR (30))
BEGIN
	DELETE FROM CARGO 
	WHERE ID_CARGO=IDCARGO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_USUARIO
(IN NOMBREUSUARIO INT, IN CONTRASEÑAUSUARIO VARCHAR (30),IN IDVENDEDORFKUSUARIO INT,IN IDCLIENTEFKUSUARIO INT,IN IDCARGOFKUSUARIO INT)
BEGIN
	DELETE FROM USUARIO 
	WHERE NOMBRE_USUARIO=NOMBREUSUARIO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_SUBASTA (IN IDSUBASTA INT)
BEGIN
	DELETE FROM SUBASTA 
	WHERE ID_SUBASTA=IDSUBASTA;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_PUJA_SUBASTA(IN IDPUJASUBASTA INT)
BEGIN
	DELETE FROM PUJA_SUBASTA 
	WHERE ID_PUJA_SUBASTA=IDPUJASUBASTA;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_DESCRIPCION_PRODUCTON (IN IDDESCRIPCIONPRODUCTO INT)
BEGIN
	DELETE FROM DESCRIPCION_PRODUCTO 
	WHERE ID_DESCRIPCION_PRODUCTO=IDDESCRIPCIONPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_PRODUCTO (IN IDPRODUCTO INT)
BEGIN
	DELETE FROM PRODUCTO 
	WHERE ID_PRODUCTO=IDPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_EXPERTO (IN IDEXPERTO INT)
BEGIN
	DELETE FROM EXPERTO 
	WHERE ID_EXPERTO=IDEXPERTO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_CLIENTE_PEDIDO (IN IDDETALLECLIENTEPEDIDO INT)
BEGIN
	DELETE FROM DETALLE_CLIENTE_PEDIDO 
	WHERE ID_DETALLE_CLIENTE_PEDIDO=IDDETALLECLIENTEPEDIDO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_DESCRIPCION_PRODUCTO (IN IDDETALLEDESCRIPCIONPRODUCTO INT)
BEGIN
	DELETE FROM  DETALLE_DESCRIPCION_PRODUCTO 
	WHERE  ID_DETALLE_DESCRIPCION_PRODUCTO=IDDETALLEDESCRIPCIONPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ELIMINAR_DETALLE_PUJA_SUBASTA (IN IDDETALLEPUJASUBASTA INT)
BEGIN
	DELETE FROM  DETALLE_PUJA_SUBASTA 
	WHERE ID_DETALLE_PUJA_SUBASTA=IDDETALLEPUJASUBASTA;
END$