USE TMARKETUSED

DELIMITER $
CREATE PROCEDURE INSERTAR_TIPO_PAGO
(IN IDTIPOPAGO INT,IN NOMTIPOPAGO VARCHAR (30))
BEGIN
INSERT INTO TIPO_PAGO (ID_TIPO_PAGO,NOMBRE_TIPO_PAGO)
VALUES (IDTIPOPAGO, NOMTIPOPAGO);
END$

INSERT INTO TIPO_PAGO VALUES (01,"Efectivo")

DELIMITER $
CREATE PROCEDURE INSERTAR_COMPRA
(IN IDCOMPRA INT, IN FECHACOMPRA DATETIME,IN TOTALCOMPRA FLOAT)
BEGIN
INSERT INTO COMPRA (ID_COMPRA,FECHA_COMPRA,TOTAL_COMPRA)
VALUES(IDCOMPRA, FECHACOMPRA,TOTALCOMPRA);
END$

INSERT INTO COMPRA VALUES(10,"2023/06/23",100000)

DELIMITER $
CREATE PROCEDURE INSERTAR_VENTA 
(IN IDVENTA INT, IN HORAVENTA DATETIME,IN NOMBREPRODUCTOVENTA VARCHAR(30),IN FECHAVENTA DATETIME)
BEGIN
INSERT INTO VENTA (ID_VENTA,HORA_VENTA,NOMBRE_PROODUCTO_VENTA,FECHA_VENTA)
VALUES(IDVENTA, HORAVENTA, NOMBREPRODUCTOVENTA, FECHAVENTA);
END$

INSERT INTO VENTA VALUES(20,"","Silla Gamer","2023/01/12") 

select *from venta
DELIMITER $
CREATE PROCEDURE INSERTAR_ENVIO 
(IN IDENVIO INT, IN NOMBREENVIO VARCHAR (30),IN DIRECCIONENVIO VARCHAR(50),IN FECHALLEGADAENVIO DATETIME)
BEGIN
INSERT INTO ENVIO (ID_ENVIO,NOMBRE_ENVIO,DIRECCION_ENVIO,FECHA_LLEGADA_ENVIO)
VALUES(IDENVIO, NOMBREENVIO, DIRECCIONENVIO, FECHALLEGADAENVIO);
END

INSERT INTO ENVIO VALUES(30,"Envio silla"," Calle 31 sur # 12","2023/01/23") 

DELIMITER $
CREATE PROCEDURE INSERTAR_PEDIDO 
(IN IDPEDIDO INT, IN NOMBREPEDIDO VARCHAR (30),IN NOMBREPRODUCTO VARCHAR(30),IN FECHAREGISTRADAPEDIDO DATETIME, IN PRECIO_PEDIDO FLOAT)
BEGIN
INSERT INTO PEDIDO (ID_PEDIDO,NOMBRE_PEDIDO,NOMBRE_PRODUCTO,FECHA_REGISTRADA_PEDIDO,PRECIO_PEDIDO)
VALUES(IDPEDIDO, NOMBREPEDIDO, NOMBREPRODUCTO, FECHAREGISTRADAPEDIDO, PRECIO_PEDIDO);
END$

INSERT INTO PEDIDO VALUES(40,"envio 1","silla gamer","2023/01/23","100000") 

DELIMITER $
CREATE PROCEDURE INSERTAR_CLIENTE 
(IN IDCLIENTE INT, IN NOMBRECLIENTE VARCHAR (30),IN TEL INT,IN FECHANACCLIENTE DATETIME, IN EDADCLIENTE INT)
BEGIN
INSERT INTO CLIENTE (ID_CLIENTE,NOMBRE_CLIENTE,TELEFONO,FECHA_NAC_CLIENTE,EDAD_CLIENTE)
VALUES(IDCLIENTE, NOMBRECLIENTE, TEL, FECHANACCLIENTE, EDADCLIENT);
END$

INSERT INTO CLIENTE VALUES(40,"Kevin",3222161514,"2005/12/28",18)

DELIMITER $
CREATE PROCEDURE INSERTAR_VENDEDOR
(IN IDVENDEDOR INT, IN NOMBREVENDEDOR VARCHAR (30),IN TELEFONOVENDEDOR INT)
BEGIN
INSERT INTO VENDEDOR (ID_VENDEDOR, NOMBRE_VENDEDOR, TELEFONO_VENDEDOR)
VALUES(IDVENDEDOR,NOMBREVENDEDOR, TELEFONOVENDEDOR);
END$

INSERT INTO VENDEDOR VALUES(50,"Martin",3123600258)

DELIMITER $
CREATE PROCEDURE INSERTAR_CARGO
(IN IDCARGO INT, IN NOMBRECARGO VARCHAR (30))
BEGIN
INSERT INTO CARGO (ID_CARGO, NOMBRE_CARGO)
VALUES(IDCARGO, NOMBRECARGO);
END$

INSERT INTO CARGO VALUES(60,"vendedor")

SELECT * FROM USUARIO

DELIMITER $
CREATE PROCEDURE INSERTAR_USUARIO
(IN NOMBREUSUARIO INT, IN CONTRASEÑAUSUARIO VARCHAR (30),IN IDVENDEDORFKUSUARIO INT,IN IDCLIENTEFKUSUARIO INT,IN IDCARGOFKUSUARIO INT)
BEGIN
INSERT INTO USUARIO (NOMBRE_USUARIO, CONTRASEÑA_USUARIO, ID_VENDEDOR_FK_USUARIO,ID_CLIENTE_FK_USUARIO,ID_CARGO_FK_USUARIO)
VALUES(NOMBREUSUARIO,CONTRASEÑAUSUARIO, IDVENDEDORFKUSUARIO,IDCLIENTEFKUSUARIO,IDCARGOFKUSUARIO);
END$

INSERT INTO USUARIO VALUES(70,"kEVIN2005","Kevin28",40,50,60)

DELIMITER $
CREATE PROCEDURE INSERTAR_SUBASTA
(IN IDSUBASTA INT, IN NOMBRESUBASTA VARCHAR (30),IN FECHASUBASTA DATETIME,IN PRECIOMINIMOSUBASTA FLOAT)
BEGIN
INSERT INTO SUBASTA (ID_SUBASTA, NOMBRE_SUBASTA, FECHA_SUBASTA, PRECIO_MINIMO_SUBASTA)
VALUES(IDSUBASTA, NOMBRESUBASTA, FECHASUBASTA, PRECIOMINIMOSUBASTA);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PUJA_SUBASTA
(IN IDPUJASUBASTA INT, IN NOMBREPUJASUBASTA VARCHAR (30),IN TIEMPOLIMITEPUJASUBASTA DATETIME,IN CANTIDADUSUARIOSLIMITEPUJASUBASTA INT)
BEGIN
INSERT INTO PUJA_SUBASTA (ID_PUJA_SUBASTA, NOMBRE_PUJA_SUBASTA, TIEMPO_LIMITE_PUJA_SUBASTA, CANTIDAD_USUARIOS_LIMITE_PUJA_SUBASTA)
VALUES(IDPUJASUBASTA, NOMBREPUJASUBASTA, TIEMPOLIMITEPUJASUBASTA, CANTIDADUSUARIOSLIMITEPUJASUBASTA);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DESCRIPCION_PRODUCTO
(IN IDDESCRIPCIONPRODUCTO INT, IN PRODUCTODESCRIPCIONPRODUCTO VARCHAR (50),IN CANTIDADDESCRIPCIONPRODUCTO INT,IN PRECIODESCRIPCIONPRODUCTO FLOAT)
BEGIN
INSERT INTO DESCRIPCION_PRODUCTO ( ID_DESCRIPCION_PRODUCTO, PRODUCTO_DESCRIPCION_PRODUCTO, CANTIDAD_DESCRIPCION_PRODUCTO, PRECIO_DESCRIPCION_PRODUCTO )
VALUES(IDDESCRIPCIONPRODUCTO,PRODUCTODESCRIPCIONPRODUCTO, CANTIDADDESCRIPCIONPRODUCTO, PRECIODESCRIPCIONPRODUCTO );
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCTO
(IN IDPRODUCTO INT, IN NOMBREPRODUCTO VARCHAR (50),IN PRECIOPRODUCTO FLOAT)
BEGIN
INSERT INTO PRODUCTO ( ID_PRODUCTO, NOMBRE_PRODUCTO, PRECIO_PRODUCTO )
VALUES(IDPRODUCTO, NOMBREPRODUCTO, PRECIOPRODUCTO );
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_EXPERTO
(IN IDEXPERTO INT, IN NOMBREEXPERTO VARCHAR (50),IN TELEFONOEXPERTO INT)
BEGIN
INSERT INTO EXPERTO ( ID_EXPERTO, NOMBRE_EXPERTO, TELEFONO_EXPERTO)
VALUES( IDEXPERTO, NOMBREEXPERTO, TELEFONOEXPERTO );
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_CLIENTE_PEDIDO (IN IDDETALLECLIENTEPEDIDO INT,IN IDPEDIDOFKDETALLECLIENTEPEDIDO INT,IN IDCLIENTEDETALLECLIENTEPEDIDO INT)
BEGIN
INSERT INTO DETALLE_CLIENTE_PEDIDO (ID_DETALLE_CLIENTE_PEDIDO, ID_PEDIDO_FK_DETALLE_CLIENTE_PEDIDO, ID_CLIENTE_DETALLE_CLIENTE_PEDIDO)
VALUES (IDDETALLECLIENTEPEDIDO, IDPEDIDOFKDETALLECLIENTEPEDIDO, IDCLIENTEDETALLECLIENTEPEDIDO);
END$

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_DESCRIPCION_PRODUCTO (IN IDDETALLEDESCRIPCIONPRODUCTO INT,IN IDDESCRIPCIONPRODUCTOFK_DETALLE_DESCRIPCION_PRODUCTO INT,IN ID_PRODUCTO_DETALLE_DESCRIPCION_PRODUCTO INT)
BEGIN
INSERT INTO DETALLE_DESCRIPCION_PRODUCTO (ID_DETALLE_DESCRIPCION_PRODUCTO, ID_DESCRIPCION_PRODUCTO_FK_DETALLE_DESCRIPCION_PRODUCTO, ID_PRODUCTO_DETALLE_DESCRIPCION_PRODUCTO )
VALUES (IDDETALLEDESCRIPCIONPRODUCTO, IDDESCRIPCIONPRODUCTOFKDETALLEDESCRIPCIONPRODUCTO, IDPRODUCTODETALLEDESCRIPCIONPRODUCTO );
END

DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PUJA_SUBASTA (IN IDDETALLEPUJASUBASTA INT,IN IDPUJASUBASTAFKDETALLEPUJASUBASTA INT,IN IDSUBASTADETALLEDETALLEPUJASUBASTA INT)
BEGIN
INSERT INTO DETALLE_PUJA_SUBASTA (ID_DETALLE_PUJA_SUBASTA, ID_PUJA_SUBASTA_FK_DETALLE_PUJA_SUBASTA, ID_SUBASTA_DETALLE_DETALLE_PUJA_SUBASTA )
VALUES (IDDETALLEPUJASUBASTA, IDPUJASUBASTAFKDETALLEPUJASUBASTA, IDSUBASTADETALLEDETALLEPUJASUBASTA );
END$


