USE TMARKETUSED

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_TIPO_PAGO
(IN IDTIPOPAGO INT,IN NOMTIPOPAGO VARCHAR (30))
BEGIN
	UPDATE TIPO_PAGO
	SET ID_TIPO_PAGO=IDTIPOPAGO, NOMBRE_TIPO_PAGO=NOMTIPOPAGO
WHERE ID_TIPO_PAGO=IDTIPOPAGO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_COMPRA
(IN IDCOMPRA INT, IN FECHACOMPRA DATETIME,IN TOTALCOMPRA FLOAT)
BEGIN
	UPDATE COMPRA 
    SET ID_COMPRA=IDCOMPRA, FECHA_COMPRA=FECHACOMPRA, TOTAL_COMPRA=TOTALCOMPRA
WHERE ID_COMPRA=IDCOMPRA;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VENTA 
(IN IDVENTA INT, IN HORAVENTA DATETIME,IN NOMBREPRODUCTOVENTA VARCHAR(30),IN FECHAVENTA DATETIME)
BEGIN
	UPDATE VENTA 
    SET ID_VENTA=IDVENTA, HORA_VENTA=HORAVENTA, NOMBRE_PROODUCTO_VENTA=NOMBREPRODUCTOVENTA, FECHA_VENTA=FECHAVENTA
WHERE ID_VENTA=IDVENTA;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_ENVIO 
(IN IDENVIO INT, IN NOMBREENVIO VARCHAR (30),IN DIRECCIONENVIO VARCHAR(50),IN FECHALLEGADAENVIO DATETIME)
BEGIN
	UPDATE ENVIO 
    SET ID_ENVIO=IDENVIO, NOMBRE_ENVIO=NOMBREENVIO ,DIRECCION_ENVIO=DIRECCIONENVIO, FECHA_LLEGADA_ENVIO=FECHALLEGADAENVIO
WHERE ID_ENVIO=IDENVIO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PEDIDO 
(IN IDPEDIDO INT, IN NOMBREPEDIDO VARCHAR (30),IN NOMBREPRODUCTO VARCHAR(30),IN FECHAREGISTRADAPEDIDO DATETIME, IN PRECIO_PEDIDO FLOAT)
BEGIN
	UPDATE PEDIDO 
    SET ID_PEDIDO=IDPEDIDO,NOMBRE_PEDIDO=NOMBREPEDIDO,NOMBRE_PRODUCTO=NOMBREPRODUCTO,FECHA_REGISTRADA_PEDIDO=FECHAREGISTRADAPEDIDO,PRECIO_PEDIDO=PRECIO_PEDIDO
WHERE ID_PEDIDO=IDPEDIDO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CLIENTE 
(IN IDCLIENTE INT, IN NOMBRECLIENTE VARCHAR (30),IN TEL INT,IN FECHANACCLIENTE DATETIME, IN EDADCLIENTE INT)
BEGIN
	UPDATE CLIENTE 
    SET ID_CLIENTE=IDCLIENTE, NOMBRE_CLIENTE=NOMBRECLIENTE, TELEFONO=TEL, FECHA_NAC_CLIENTE=FECHANACCLIENTE, EDAD_CLIENTE=EDADCLIENTE
WHERE ID_CLIENTE=IDCLIENTE;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_VENDEDOR
(IN IDVENDEDOR INT, IN NOMBREVENDEDOR VARCHAR (30),IN TELEFONOVENDEDOR INT)
BEGIN
	UPDATE VENDEDOR 
    SET ID_VENDEDOR=IDVENDEDOR, NOMBRE_VENDEDOR=NOMBREVENDEDOR, TELEFONO_VENDEDOR=TELEFONOVENDEDOR
WHERE ID_VENDEDOR=IDVENDEDOR;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CARGO
(IN IDCARGO INT, IN NOMBRECARGO VARCHAR (30))
BEGIN
	UPDATE CARGO 
    SET ID_CARGO=IDCARGO, NOMBRE_CARGO=NOMBRECARGO
WHERE ID_CARGO=IDCARGO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO
(IN NOMBREUSUARIO INT, IN CONTRASEÑAUSUARIO VARCHAR (30),IN IDVENDEDORFKUSUARIO INT,IN IDCLIENTEFKUSUARIO INT,IN IDCARGOFKUSUARIO INT)
BEGIN
	UPDATE USUARIO 
    SET NOMBRE_USUARIO=NOMBREUSUARIO, CONTRASEÑA_USUARIO=CONTRASEÑAUSUARIO, ID_VENDEDOR_FK_USUARIO=IDVENDEDORFKUSUARIO,ID_CLIENTE_FK_USUARIO=IDCLIENTEFKUSUARIO,ID_CARGO_FK_USUARIO=IDCARGOFKUSUARIO
WHERE NOMBRE_USUARIO=NOMBREUSUARIO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_SUBASTA
(IN IDSUBASTA INT, IN NOMBRESUBASTA VARCHAR (30),IN FECHASUBASTA DATETIME,IN PRECIOMINIMOSUBASTA FLOAT)
BEGIN
	UPDATE SUBASTA 
    SET ID_SUBASTA=IDSUBASTA, NOMBRE_SUBASTA=NOMBRESUBASTA, FECHA_SUBASTA=FECHASUBASTA, PRECIO_MINIMO_SUBASTA=PRECIOMINIMOSUBASTA
WHERE ID_SUBASTA=IDSUBASTA;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PUJA_SUBASTA
(IN IDPUJASUBASTA INT, IN NOMBREPUJASUBASTA VARCHAR (30),IN TIEMPOLIMITEPUJASUBASTA DATETIME,IN CANTIDADUSUARIOSLIMITEPUJASUBASTA INT)
BEGIN
	UPDATE PUJA_SUBASTA 
    SET ID_PUJA_SUBASTA=IDPUJASUBASTA, NOMBRE_PUJA_SUBASTA=NOMBREPUJASUBASTA, TIEMPO_LIMITE_PUJA_SUBASTA=TIEMPOLIMITEPUJASUBASTA, CANTIDAD_USUARIOS_LIMITE_PUJA_SUBASTA=CANTIDADUSUARIOSLIMITEPUJASUBASTA
WHERE ID_PUJA_SUBASTA=IDPUJASUBASTA;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DESCRIPCION_PRODUCTO
(IN IDDESCRIPCIONPRODUCTO INT, IN PRODUCTODESCRIPCIONPRODUCTO VARCHAR (50),IN CANTIDADDESCRIPCIONPRODUCTO INT,IN PRECIODESCRIPCIONPRODUCTO FLOAT)
BEGIN
	UPDATE DESCRIPCION_PRODUCTO 
    SET ID_DESCRIPCION_PRODUCTO=IDDESCRIPCIONPRODUCTO, PRODUCTO_DESCRIPCION_PRODUCTO=PRODUCTODESCRIPCIONPRODUCTO, CANTIDAD_DESCRIPCION_PRODUCTO=CANTIDADDESCRIPCIONPRODUCTO, PRECIO_DESCRIPCION_PRODUCTO= PRECIODESCRIPCIONPRODUCTO
WHERE ID_DESCRIPCION_PRODUCTO=IDDESCRIPCIONPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PRODUCTO
(IN IDPRODUCTO INT, IN NOMBREPRODUCTO VARCHAR (50),IN PRECIOPRODUCTO FLOAT)
BEGIN
	UPDATE PRODUCTO 
    SET ID_PRODUCTO=IDPRODUCTO, NOMBRE_PRODUCTO=NOMBREPRODUCTO, PRECIO_PRODUCTO=PRECIOPRODUCTO
WHERE ID_PRODUCTO=IDPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_EXPERTO
(IN IDEXPERTO INT, IN NOMBREEXPERTO VARCHAR (50),IN TELEFONOEXPERTO INT)
BEGIN
	UPDATE EXPERTO 
    SET ID_EXPERTO=IDEXPERTO, NOMBRE_EXPERTO=NOMBREEXPERTO, TELEFONO_EXPERTO=TELEFONOEXPERTO
WHERE ID_EXPERTO=IDEXPERTO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_CLIENTE_PEDIDO 
(IN IDDETALLECLIENTEPEDIDO INT,IN IDPEDIDOFKDETALLECLIENTEPEDIDO INT,IN IDCLIENTEDETALLECLIENTEPEDIDO INT)
BEGIN
	UPDATE DETALLE_CLIENTE_PEDIDO 
    SET ID_DETALLE_CLIENTE_PEDIDO=IDDETALLECLIENTEPEDIDO, ID_PEDIDO_FK_DETALLE_CLIENTE_PEDIDO=IDPEDIDOFKDETALLECLIENTEPEDIDO, ID_CLIENTE_DETALLE_CLIENTE_PEDIDO=IDCLIENTEDETALLECLIENTEPEDIDO
WHERE ID_DETALLE_CLIENTE_PEDIDO=IDDETALLECLIENTEPEDIDO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_DESCRIPCION_PRODUCTO 
(IN IDDETALLEDESCRIPCIONPRODUCTO INT,IN IDDESCRIPCIONPRODUCTOFK_DETALLE_DESCRIPCION_PRODUCTO INT,IN ID_PRODUCTO_DETALLE_DESCRIPCION_PRODUCTO INT)
BEGIN
	UPDATE DETALLE_DESCRIPCION_PRODUCTO 
    SET ID_DETALLE_DESCRIPCION_PRODUCTO=IDDETALLEDESCRIPCIONPRODUCTO, ID_DESCRIPCION_PRODUCTO_FK_DETALLE_DESCRIPCION_PRODUCTO=IDDESCRIPCIONPRODUCTOFKDETALLEDESCRIPCIONPRODUCTO, ID_PRODUCTO_DETALLE_DESCRIPCION_PRODUCTO=IDPRODUCTODETALLEDESCRIPCIONPRODUCTO
WHERE  ID_DETALLE_DESCRIPCION_PRODUCTO=IDDETALLEDESCRIPCIONPRODUCTO;
END$

DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PUJA_SUBASTA 
(IN IDDETALLEPUJASUBASTA INT,IN IDPUJASUBASTAFKDETALLEPUJASUBASTA INT,IN IDSUBASTADETALLEDETALLEPUJASUBASTA INT)
BEGIN
	UPDATE DETALLE_PUJA_SUBASTA 
    SET ID_DETALLE_PUJA_SUBASTA=IDDETALLEPUJASUBASTA, ID_PUJA_SUBASTA_FK_DETALLE_PUJA_SUBASTA=IDPUJASUBASTAFKDETALLEPUJASUBASTA, ID_SUBASTA_DETALLE_DETALLE_PUJA_SUBASTA=IDSUBASTADETALLEDETALLEPUJASUBASTA
WHERE ID_DETALLE_PUJA_SUBASTA=IDDETALLEPUJASUBASTA;
END$
